### PR TITLE
cdt demo add zoom / drag move support

### PR DESCRIPTION
**Pull request by baiwenlei**
cdt-zooming-dragging-small

### CODE REVIEW

**Comment by artem-ogre** [comment]
Thank you for the contribution! That's a useful feature. I will try to take a closer look when I have time.

**Comment by baiwenlei** [comment]
You are welcome. Thanks for the wonderful library!
There some information I think you should know before review:
1. demo code use c++17 std::optional feature 
2. because of QT draw point bug, there is some case that the point is painted like a short line.
image

**the reason is here:**
https://stackoverflow.com/questions/52194141/why-does-qpainterdrawpoint-draw-a-horizontal-line-segment?rq=1

**Comment by artem-ogre** [comment]
Thank you for the clarifications.
> You are welcome. Thanks for the wonderful library!
> There some information I think you should know before review:
> 
>     1. demo code use c++17 std::optional feature
Yes, I think I will re-implement it without `std::optional` not to enforce additional constraints on the c++ standard.
>     2. because of QT draw point bug, there is some case that the point is painted like a short line
Yes, I saw this. I will re-implement transform to be applied to each point instead similarly as it is done now to work-around this issue.

I have a question about this line `CONFIG-=app_bundle`. Could you please explain what's the purpose? I don't have macOS available for testing right now.

**Comment by baiwenlei** [comment]
> Thank you for the clarifications.
> 
> > You are welcome. Thanks for the wonderful library!
> > There some information I think you should know before review:
> > ```
> > 1. demo code use c++17 std::optional feature
> > ```
> 
> Yes, I think I will re-implement it without `std::optional` not to enforce additional constraints on the c++ standard.
> 
> > ```
> > 2. because of QT draw point bug, there is some case that the point is painted like a short line
> > ```
> 
> Yes, I saw this. I will re-implement transform to be applied to each point instead similarly as it is done currently to work-around this issue.
> 
> I have a question about this line `CONFIG-=app_bundle`. Could you please explain what's the purpose? I don't have macOS available for testing right now.

On Mac platform, the app is default a package folder, with the actual executable file and all the resources in it. Because the cdt executable program need to load all the files under the folder "**cdt-executable-folder**/test files/",  so user need to open that folder and copy "test file" folder to that folder. That's an extra step, and the package folder can't just click and open, you need right click mouse and select "open package bundle" to open that folder.

**with CONFIG-=app_bundle**
image

**without CONFIG-=app_bundle**
image

The content of the package

image

**Comment by artem-ogre** [comment]
Hello,

I've cleaned up the implementation, and implemented it without using any modern c++ (for better compatibility).
Please take a look: https://github.com/artem-ogre/CDT/pull/9

I've credited you in the commit comment: please let me know if that's OK.

**Comment by artem-ogre** [comment]
I've also extended contributors list in the README.md. 
Thank you again for the contribution.

**Comment by baiwenlei** [comment]
It's OK, thanks for the contributors extension.

**Pull request closed without merging**
